sync CE22 updates and Amlogic-ng fixes

diff --git a/tools/update-scan b/tools/update-scan
--- a/tools/update-scan
+++ b/tools/update-scan
@@ -11,6 +11,9 @@ set -e
 command -v curl >/dev/null 2>&1 || die "please install curl"
 command -v jq >/dev/null 2>&1 || die "please install jq"
 
+# check for autoupdate argument
+[[ "${AUTO_UPDATE}" == "yes" ]] && echo "running as auto update" >&2
+
 # global vars
 PACKAGES_CURRENT=""
 PACKAGES_IGNORED=""
@@ -27,9 +30,11 @@ test_github_api() {
       echo "Github api usage activated"
       github_api="yes"
     else
+      msg=$(curl -m 5 -sL -I "${github_api_token}" https://api.github.com/user || true)
       message="\n your Github token is not working\n"
       message+=" github_token=${github_token}\n"
       message+=" github_user=${github_user}\n"
+      message+=" ${msg}\n"
       die "${message}"
     fi
   else
@@ -48,35 +53,53 @@ check_for_update() {
 
   # source variables from package.mk
   PKG_NAME="$(grep -oP -m 1 '(?<=PKG_NAME=\").*(?=\")' ${1} || true)"
-  PKG_VERSION="$(grep -oP -m 1 '(?<=PKG_VERSION=\").*(?=\")' ${1} || true)"
   eval PKG_URL="$(grep -oP -m 1 '(?<=PKG_URL=\").*(?=\")' ${1} || true)"
+  case ${PKG_NAME} in
+    jellyfin)
+      PKG_VERSION="$(grep -oP -m 1 '(?<=PKG_VERSION_NUMBER=\").*(?=\")' ${1} || true)"
+      ;;
+    *)
+      PKG_VERSION="$(grep -oP -m 1 '(?<=PKG_VERSION=\").*(?=\")' ${1} || true)"
+      ;;
+  esac
 
-  # check if version and url are empty or self hosted by us and ignore those packages
-  if [ -z "${PKG_VERSION}" ] || [[ ${PKG_VERSION} == '$(get_pkg_version '* ]] || [ -z "${PKG_URL}" ] || [[ "${PKG_URL}" == "$DISTRO_SRC"* ]]; then
-    PACKAGES_IGNORED+="${PKG_NAME} "
-    return
+  # check the version of some packages even if they do not have a PKG_URL
+  # the PKG_WITHOUT_URLS is space separated
+  PKGS_WITHOUT_URLS="jellyfin"
+  if [[ ! " ${PKG_NAME} " == *" ${PKGS_WITHOUT_URLS} "* ]]; then
+    # check if version and url are empty or self hosted by us and ignore those packages
+    if [ -z "${PKG_VERSION}" ] || [[ ${PKG_VERSION} == '$(get_pkg_version '* ]] || [ -z "${PKG_URL}" ] || [[ "${PKG_URL}" == "$DISTRO_SRC"* ]]; then
+      PACKAGES_IGNORED+="${PKG_NAME} "
+      return
+    fi
   fi
 
   upstream_version=""
 
   if [[ "${github_api}" = "yes" ]]; then
-    case ${PKG_NAME} in
-      aspnet6-runtime)
-        upstream_version="$(curl -m 5 -sL ${github_api_token} https://api.github.com/repos/dotnet/runtime/releases | jq -r '[.[] | select(.prerelease==false) | select(.tag_name | match("v6.0")) | .tag_name][0] | sub("v";"")')"
-        ;;
-      aspnet8-runtime)
-        upstream_version="$(curl -m 5 -sL ${github_api_token} https://api.github.com/repos/dotnet/runtime/releases | jq -r '[.[] | select(.tag_name | match("v8.0")) | .tag_name][0] | sub("v";"")')"
-        ;;
-    esac
+    # get aspnet??-runtime version from github (not Anitya)
+    aspnet_ver=$(echo ${PKG_NAME} | sed -n 's/aspnet\(.*\)-runtime/\1/p')
+    if [[ ! -z "${aspnet_ver}" ]]; then
+      page_num=1
+      while [ ${page_num} -le 10 ]; do
+        curl_output="$(curl -m 5 -sL ${github_api_token} https://api.github.com/repos/dotnet/runtime/releases?per_page=100\&page=${page_num})"
+        upstream_version="$(echo ${curl_output} | jq -r "[.[] | select(.prerelease==false) | select(.tag_name | match(\"v${aspnet_ver}.0\")) | .tag_name][0] | sub(\"v\";\"\")?")"
+        [[ $(echo "${curl_output}" | jq 'length == 0') ]] && break
+        [[ -z "${upstream_version}" ]] && ((page_num++)) || break
+      done
+    fi
   fi
 
   if [ -z "${upstream_version}" ]; then
     # check if package exists at tracker
-    RMO_API_RESPONSE=$(curl -m 5 -sL "https://release-monitoring.org/api/project/LibreELEC/${PKG_NAME}" || true)
-    upstream_version=$(echo "${RMO_API_RESPONSE}" | jq -r '.version' || true)
+    RMO_API_RESPONSE=$(curl -m 5 -sL "https://release-monitoring.org/api/v2/packages/?name=${PKG_NAME}&distribution=LibreELEC" || true)
+    upstream_version=$(echo "${RMO_API_RESPONSE}" | jq -r '.items[0].version' || true)
 
     # special handling based on release-monitoring formatting
     case ${PKG_NAME} in
+      krb5)
+        upstream_version=${upstream_version//-final/}
+        ;;
       lm_sensors)
         upstream_version=${upstream_version//-/.}
         ;;
@@ -91,8 +114,8 @@ check_for_update() {
     github_repos=$(echo "${PKG_URL}" | grep -oP '(?<=https:\/\/github.com\/)?[0-9A-Za-z._-]+\/[0-9A-Za-z._-]+(?=/archive|/tags|/releases)')
     le_master_version_date="Commit date: $(curl -m 5 -sL ${github_api_token} https://api.github.com/repos/${github_repos}/git/commits/${PKG_VERSION} | jq -r '.committer.date')"
     upstream_default_branch=$(curl -m 5 -sL "${github_api_token}" "https://api.github.com/repos/${github_repos}" | jq -r '.default_branch')
-    upstream_latest_commit=$(curl -m 5 -sL "${github_api_token}" "https://api.github.com/repos/${github_repos}/git/refs/heads/${upstream_default_branch}" | jq -r '.object.url')
-    upstream_latest_commit_date=$(curl -m 5 -sL "${github_api_token}" "${upstream_latest_commit}" | jq -r '.committer.date')
+    upstream_latest_commit=$(curl -m 5 -sL "${github_api_token}" "https://api.github.com/repos/${github_repos}/git/refs/heads/${upstream_default_branch}" | jq -r '.object.url' || true)
+    upstream_latest_commit_date=$(curl -m 5 -sL "${github_api_token}" "${upstream_latest_commit}" | jq -r '.committer.date' || true)
     GH_API_TAG=$(curl -m 5 -sL "${github_api_token}" "https://api.github.com/repos/${github_repos}/tags")
     upstream_latest_tag=$(echo "${GH_API_TAG}" | jq -r '.[0].name')
     upstream_latest_tag_url=$(echo "${GH_API_TAG}" | jq -r '.[0].commit.url')
@@ -100,7 +123,7 @@ check_for_update() {
 
     # compare upstream with local version
     if [ "${PKG_VERSION}" != "${upstream_latest_commit##*/}" ]; then
-      # get upstream tag informations
+      # get upstream tag information
       if [ "${upstream_latest_tag}" != "null" ]; then
         tag=" | TAG: ${upstream_latest_tag} (${upstream_latest_tag_date%T*})"
       else
@@ -113,7 +136,7 @@ check_for_update() {
       upstream_version="${upstream_latest_commit##*/}"
     fi
   elif [ "${upstream_version}" = "null" ]; then
-    if [[ $(echo "${RMO_API_RESPONSE}" | jq -r '.error') =~ "No package" ]]; then
+    if [[ $(echo "${RMO_API_RESPONSE}" | jq -r '.total_items') =~ "0" ]]; then
       # package is not on tracker or github
       PACKAGES_NOT_REGISTERED+="${PKG_NAME} "
       return
@@ -124,7 +147,9 @@ check_for_update() {
   fi
 
   # print version output line
-  if [ ! -z "${API}" ]; then
+  if [[ "${AUTO_UPDATE}" == "yes" ]] && [ "${PKG_VERSION}" != "${upstream_version}" ]; then
+    echo "${PKG_NAME} ${PKG_VERSION} ${upstream_version}"
+  elif [ ! -z "${API}" ]; then
     printf "%s %s %s" "${PKG_NAME}" "${PKG_VERSION}" "${upstream_version}"
     printf '\n'
   elif [ "${PKG_VERSION}" != "${upstream_version}" ]; then
@@ -136,10 +161,16 @@ check_for_update() {
 }
 
 # create list of packages
-if [ -n "${1}" ]; then
-  PACKAGE_LIST="$(find packages/ -type d -name ${1})/package.mk"
-  if [ ! -f "${PACKAGE_LIST}" ]; then
-    die "Package not found: ${1}"
+if [ $# -gt 0 ]; then
+  for pkg in $*; do
+    for dir in $(find packages/ -type d -name ${pkg}); do
+      if [ -f "${dir}/package.mk" ]; then
+        PACKAGE_LIST+=" ${dir}/package.mk"
+      fi
+    done
+  done
+  if [ -z "${PACKAGE_LIST}" ]; then
+    die "Packages not found: $*"
   fi
 else
   PACKAGE_LIST="$(
@@ -152,7 +183,11 @@ else
   )"
 fi
 
-if [ -z "${API}" ]; then
+if [[ "${AUTO_UPDATE}" == "yes" ]]; then
+  for check_version in ${PACKAGE_LIST}; do
+    check_for_update "${check_version}"
+  done
+elif [ -z "${API}" ]; then
   # test github api availability
   test_github_api
 
